USE MASTER
GO

IF EXISTS(SELECT * FROM SYSDATABASES WHERE NAME = 'AALVES3')
	DROP DATABASE AALVES3
GO

CREATE DATABASE AALVES3
GO
USE AALVES3
GO
CREATE TABLE CURSO (
	ID_CURSO INT PRIMARY KEY IDENTITY(1,1),
	NOME     VARCHAR(50) NOT NULL
)
GO
CREATE TABLE PERIODO (
	ID_PERIODO  INT PRIMARY KEY IDENTITY(1,1),
	NOME        VARCHAR(50) NOT NULL,
	HORA_INICIO TIME(0) NOT NULL,
	HORA_TERMIN TIME(0) NOT NULL
)
GO
CREATE TABLE CARGO (
	ID_CARGO   INT PRIMARY KEY IDENTITY(1,1),
	NOME       VARCHAR(50) NOT NULL,
	ALUNO_CADS BIT NOT NULL,
	ALUNO_CONS BIT NOT NULL,
	ALUNO_EDIT BIT NOT NULL,
	PROF_CADS  BIT NOT NULL,
	PROF_CONS  BIT NOT NULL,
	PROF_EDIT  BIT NOT NULL,
	FUNC_CADS  BIT NOT NULL,
	FUNC_CONS  BIT NOT NULL,
	FUNC_EDIT  BIT NOT NULL,
	ATIV_CRIAR BIT NOT NULL,
	ATIV_CONS  BIT NOT NULL,
	ATIV_EDIT  BIT NOT NULL,
	NOTA_ATRIB BIT NOT NULL,
	NOTA_CONS  BIT NOT NULL
)
GO
CREATE TABLE ALUNO (
	ID_ALUNO INT PRIMARY KEY IDENTITY(1,1),
	NOME     VARCHAR(80) NOT NULL,
	EMAIL    VARCHAR(80) NOT NULL,
	SEXO     VARCHAR(20) NOT NULL,
	SENHA    VARCHAR(80) NOT NULL,
	RUA      VARCHAR(80) NOT NULL,
	NUM      INT NOT NULL,
	CEP      VARCHAR(9) NOT NULL,
	CIDADE   VARCHAR(50) NOT NULL,
	ESTADO   VARCHAR(30) NOT NULL,
	TELEFONE VARCHAR(20) NOT NULL,
	CADASTRO DATE DEFAULT GETDATE(),
	ATIVO    BIT NOT NULL
)
GO
CREATE TABLE CURSO_ALUNO (
	ID_ALUNO INT FOREIGN KEY REFERENCES ALUNO(ID_ALUNO),
	ID_CURSO INT FOREIGN KEY REFERENCES CURSO(ID_CURSO),
	CADASTRO DATETIME DEFAULT GETDATE(),
	ATIVO    BIT NOT NULL
)
GO
CREATE TABLE PERIODO_ALUNO (
	ID_ALUNO   INT FOREIGN KEY REFERENCES ALUNO(ID_ALUNO),
	ID_PERIODO INT FOREIGN KEY REFERENCES PERIODO(ID_PERIODO),
	CADASTRO   DATETIME DEFAULT GETDATE(),
	ATIVO      BIT NOT NULL
)
GO
CREATE TABLE PROFESSOR (
	ID_PROFESSOR INT PRIMARY KEY IDENTITY(1,1),
	NOME         VARCHAR(80) NOT NULL,
	SEXO         VARCHAR(20) NOT NULL,
	RG           VARCHAR(50) NOT NULL,
	CPF          VARCHAR(50) NOT NULL,
	RUA          VARCHAR(80) NOT NULL,
	NUM          INT NOT NULL,
	BAIRRO       VARCHAR(20) NOT NULL,
	CEP          VARCHAR(9) NOT NULL,
	CIDADE       VARCHAR(50) NOT NULL,
	ESTADO       VARCHAR(30) NOT NULL,
	TELEFONE     VARCHAR(20) NOT NULL,
	CELULAR      VARCHAR(20) NOT NULL,
	EMAIL        VARCHAR(80) NOT NULL,
	SENHA        VARCHAR(80) NOT NULL,
	CADASTRO     DATE DEFAULT GETDATE(),
	ATIVO        BIT NOT NULL
)
GO
CREATE TABLE FUNCIONARIO (
	ID_FUNCIONARIO INT PRIMARY KEY IDENTITY(1,1),
	NOME           VARCHAR(80) NOT NULL,
	SEXO           VARCHAR(20) NOT NULL,
	RG             VARCHAR(50) NOT NULL,
	CPF            VARCHAR(50) NOT NULL,
	RUA            VARCHAR(80) NOT NULL,
	NUM            INT NOT NULL,
	BAIRRO         VARCHAR(20) NOT NULL,
	CEP            VARCHAR(9) NOT NULL,
	CIDADE         VARCHAR(50) NOT NULL,
	ESTADO         VARCHAR(30) NOT NULL,
	TELEFONE       VARCHAR(20) NOT NULL,
	CELULAR        VARCHAR(20) NOT NULL,
	EMAIL          VARCHAR(80) NOT NULL,
	SENHA          VARCHAR(80) NOT NULL,
	CARGO          INT FOREIGN KEY REFERENCES CARGO(ID_CARGO),
	CADASTRO       DATE DEFAULT GETDATE(),
	ATIVO          BIT NOT NULL
)
GO
CREATE TABLE PROVA (
	ID_PROVA     INT PRIMARY KEY IDENTITY(1,1),
	NOME         VARCHAR(40) NOT NULL,
	DESCRICAO    VARCHAR(100) NOT NULL,
	ID_PROFESSOR INT FOREIGN KEY REFERENCES PROFESSOR(ID_PROFESSOR),
	CADASTRO     DATE DEFAULT GETDATE()
)
GO
CREATE TABLE NOTA (
	ID_PROVA    INT FOREIGN KEY REFERENCES PROVA(ID_PROVA),
	ID_ALUNO    INT FOREIGN KEY REFERENCES ALUNO(ID_ALUNO),
	LISTENING   INT NOT NULL,
	READING     INT NOT NULL,
	SPEAKING    INT NOT NULL,
	PERFORMANCE INT NOT NULL,
	CADASTRO    DATE DEFAULT GETDATE()
)
GO
CREATE TABLE TURMA (
	ID_TURMA   INT PRIMARY KEY IDENTITY(1,1),
	NOME_TURMA VARCHAR(30) NOT NULL,
    ID_CURSO   INT FOREIGN KEY REFERENCES CURSO(ID_CURSO),
    ID_PERIODO INT FOREIGN KEY REFERENCES PERIODO(ID_PERIODO)
)
GO
CREATE TABLE TURMA_ALUNO (
	ID_TURMA INT FOREIGN KEY REFERENCES TURMA(ID_TURMA),
	ID_ALUNO INT FOREIGN KEY REFERENCES ALUNO(ID_ALUNO)
)
GO
CREATE TABLE PRODUTO (
	ID_PROD   INT PRIMARY KEY IDENTITY(1,1),
	NOME_PROD VARCHAR(50) NOT NULL,
	PRECO     DECIMAL(10,2) NOT NULL,
	QNT       INT NOT NULL,
	IMAGEM    VARCHAR(50)
)
GO
CREATE TABLE PEDIDO (
	ID_PED   INT PRIMARY KEY IDENTITY(1,1),
	ID_ALUNO INT FOREIGN KEY REFERENCES ALUNO(ID_ALUNO),
	VALOR    DECIMAL(10,2) NOT NULL,
	DATA     DATETIME DEFAULT GETDATE()
)
GO
CREATE TABLE DETALHE_PEDIDO (
	ID_DET_PED INT PRIMARY KEY IDENTITY(1,1),
	ID_PED     INT FOREIGN KEY REFERENCES PEDIDO(ID_PED),
	ID_PROD    INT FOREIGN KEY REFERENCES PRODUTO(ID_PROD),
	VALOR      DECIMAL(10,2) NOT NULL,
	QNT        INT NOT NULL
)
GO
CREATE TABLE AULA (
	ID_AULA    INT PRIMARY KEY IDENTITY(1,1),
	DATA       DATE NOT NULL,
	ID_TURMA   INT FOREIGN KEY REFERENCES TURMA(ID_TURMA)
)
GO
CREATE TABLE PRESENCA (
	ID_AULA  INT FOREIGN KEY REFERENCES AULA(ID_AULA),
	ID_ALUNO INT FOREIGN KEY REFERENCES ALUNO(ID_ALUNO),
	PRESENTE BIT NOT NULL
)
GO
INSERT INTO CARGO VALUES('Master', 'true', 'true', 'true', 'true', 'true', 'true', 'true', 'true', 'true', 'true', 'true', 'true', 'true', 'true')
GO
INSERT INTO FUNCIONARIO VALUES('TESTE', 'TESTE', 'TESTE', 'TESTE', 'TESTE', 1, 'TESTE', 'TESTE', 'TESTE', 'TESTE', 'TESTE', 'TESTE', 'testet', 'teste', 1, DEFAULT, 1)
GO
select* from cargo
select * from FUNCIONARIO

--INSERT INTO ALUNO OUTPUT inserted.ID_ALUNO VALUES ('{0}','{1}','{2}','{3}','{4}', 5,'{6}','{7}','{8}','{9}', DEFAULT)
INSERT INTO CURSO VALUES('BASICO')
INSERT INTO CURSO VALUES('INTERMEDIARIO')
INSERT INTO CURSO VALUES('AVANCADO')
INSERT INTO CURSO VALUES('ESPRECO')
INSERT INTO PERIODO VALUES('MANHA', '08:00', '11:00')
INSERT INTO PERIODO VALUES('TARDE', '13:00', '16:00')
INSERT INTO PERIODO VALUES('NOITE', '19:00', '22:00')
--SELECT * FROM CURSO
--SELECT * FROM PERIODO
--SELECT * FROM ALUNO
--SELECT * FROM FUNCIONARIO
--SELECT * FROM PROFESSOR
--DELETE FROM FUNCIONARIO WHERE ID_FUNCIONARIO = 2
--SELECT * FROM CURSO_ALUNO
--SELECT * FROM PERIODO_ALUNO
--INSERT INTO CURSO VALUES(1, 'TESTE')
--INSERT INTO PERIODO VALUES(2, 'TESTE')

--SELECT ALUNO.ID_ALUNO AS ID, ALUNO.NOME, ALUNO.SEXO, CURSO.NOME AS CURSO, PERIODO.NOME AS PERIODO, ALUNO.CADASTRO FROM ALUNO
--INNER JOIN CURSO_ALUNO ON
--ALUNO.ID_ALUNO = CURSO_ALUNO.ID_ALUNO
--INNER JOIN CURSO ON
--CURSO_ALUNO.ID_CURSO = CURSO.ID_CURSO
--INNER JOIN PERIODO_ALUNO ON
--ALUNO.ID_ALUNO = PERIODO_ALUNO.ID_ALUNO
--INNER JOIN PERIODO ON
--PERIODO_ALUNO.ID_PERIODO = PERIODO.ID_PERIODO

--UPDATE ALUNO
--SET 
--NOME='',
--EMAIL='',
--SEXO='',
--SENHA='',
--RUA='',
--NUM='',
--CEP='',
--CIDADE='',
--ESTADO='',
--TELEFONE=''
--WHERE ID_ALUNO=''

--DELETE FROM CURSO_ALUNO WHERE CURSO_ALUNO.ID_ALUNO = '1'; DELETE FROM PERIODO_ALUNO WHERE PERIODO_ALUNO.ID_ALUNO = '1'; DELETE FROM ALUNO WHERE ALUNO.ID_ALUNO = '1'