USE AALVES3
GO

--LOGIN C# E JAVA
CREATE PROCEDURE USP_PROG_LOGIN
	@EMAIL VARCHAR(80),
	@SENHA VARCHAR(80)
AS
	DECLARE @VAL_EMAIL INT, @VAL_SENHA INT

	SET @VAL_EMAIL = (SELECT COUNT(ID_PROFESSOR) FROM PROFESSOR WHERE EMAIL = @EMAIL)
	SET @VAL_SENHA = (SELECT COUNT(SENHA) FROM PROFESSOR WHERE SENHA = @SENHA)
	IF ((@VAL_EMAIL = 1) AND (@VAL_SENHA = 1))
		BEGIN
			SELECT ID_PROFESSOR AS ID, NOME, ('PROFESSOR') AS CARGO FROM PROFESSOR
		END
	ELSE
		BEGIN 
			SET @VAL_EMAIL = (SELECT COUNT(ID_FUNCIONARIO) FROM FUNCIONARIO WHERE EMAIL = @EMAIL)
			SET @VAL_SENHA = (SELECT COUNT(SENHA) FROM FUNCIONARIO WHERE SENHA = @SENHA)

			IF ((@VAL_EMAIL = 1) AND (@VAL_SENHA = 1))
				BEGIN
					SELECT FUNCIONARIO.ID_FUNCIONARIO AS ID, FUNCIONARIO.NOME, CARGO.NOME AS CARGO FROM FUNCIONARIO
					INNER JOIN CARGO ON FUNCIONARIO.CARGO = CARGO.ID_CARGO
				END
			ELSE
				BEGIN 
					SELECT 0 AS ID, ('') AS NOME, ('') AS CARGO
				END
		END

--EXEC USP_PROG_LOGIN "testet", "teste"

GO


--LOGIN ASP
CREATE PROCEDURE USP_ASP_LOGIN
	@EMAIL VARCHAR(80),
	@SENHA VARCHAR(80)
AS
	DECLARE @VAL_EMAIL INT, @VAL_SENHA INT

	SET @VAL_EMAIL = (SELECT COUNT(ID_ALUNO) FROM ALUNO WHERE EMAIL = @EMAIL)
	SET @VAL_SENHA = (SELECT COUNT(SENHA) FROM ALUNO WHERE SENHA = @SENHA)
	IF ((@VAL_EMAIL = 1) AND (@VAL_SENHA = 1))
		BEGIN
			SELECT ID_ALUNO AS ID, NOME FROM ALUNO
		END
	ELSE
		BEGIN 
			SELECT 0 AS ID, ('') AS NOME
		END
--EXEC USP_ASP_LOGIN "joaoCM@gmail.com", "12345"