USE MASTER
GO

IF EXISTS(SELECT * FROM SYSDATABASES WHERE NAME = 'AALVES3')
	DROP DATABASE AALVES3
GO

CREATE DATABASE AALVES3
GO
USE AALVES3
GO
CREATE TABLE CURSO (
	ID_CURSO INT PRIMARY KEY,
	NOME     VARCHAR(50) NOT NULL
)
GO
CREATE TABLE PERIODO (
	ID_PERIODO INT PRIMARY KEY,
	NOME       VARCHAR(50) NOT NULL,
	H_INICIO   DATE,
	H_TERM     DATE
)
GO
CREATE TABLE CARGO (
	ID_CARGO   INT PRIMARY KEY IDENTITY(1,1),
	NOME       VARCHAR(50) NOT NULL,
	ATIV_CRIAR BIT NOT NULL,
	ATIV_EDIT  BIT NOT NULL,
	ATIV_CONS  BIT NOT NULL,
	NOTA_ATRIB BIT NOT NULL,
	NOTA_CONS  BIT NOT NULL,
	ALUNO_CADS BIT NOT NULL,
	ALUNO_CONS BIT NOT NULL,
	ALUNO_EDIT BIT NOT NULL,
	FUNC_CADS  BIT NOT NULL,
	FUNC_CONS  BIT NOT NULL,
	FUNC_EDIT  BIT NOT NULL,
	PROF_CADS  BIT NOT NULL,
	PROF_CONS  BIT NOT NULL,
	PROF_EDIT  BIT NOT NULL	
)
GO
CREATE TABLE ALUNO (
	ID_ALUNO INT PRIMARY KEY IDENTITY(1,1),
	NOME     VARCHAR(80) NOT NULL,
	EMAIL    VARCHAR(80) NOT NULL,
	SEXO     VARCHAR(20) NOT NULL,
	SENHA    VARCHAR(80) NOT NULL,
	RUA      VARCHAR(80) NOT NULL,
	NUM      INT NOT NULL,
	CEP      VARCHAR(9) NOT NULL,
	CIDADE   VARCHAR(50) NOT NULL,
	ESTADO   VARCHAR(30) NOT NULL,
	TELEFONE VARCHAR(20) NOT NULL,
	CADASTRO DATE DEFAULT GETDATE()
)
GO
CREATE TABLE CURSO_ALUNO (
	ID_ALUNO  INT FOREIGN KEY REFERENCES ALUNO(ID_ALUNO),
	ID_CURSO  INT FOREIGN KEY REFERENCES CURSO(ID_CURSO)
)
GO
CREATE TABLE PERIODO_ALUNO (
	ID_ALUNO   INT FOREIGN KEY REFERENCES ALUNO(ID_ALUNO),
	ID_PERIODO INT FOREIGN KEY REFERENCES PERIODO(ID_PERIODO)
)
GO
CREATE TABLE PROFESSOR (
	ID_PROFESSOR INT PRIMARY KEY IDENTITY(1,1),
	NOME         VARCHAR(80) NOT NULL,
	SEXO         VARCHAR(20) NOT NULL,
	RG           VARCHAR(50) NOT NULL,
	CPF          VARCHAR(50) NOT NULL,
	RUA          VARCHAR(80) NOT NULL,
	NUM          INT NOT NULL,
	BAIRRO       VARCHAR(20) NOT NULL,
	CEP          VARCHAR(9) NOT NULL,
	CIDADE       VARCHAR(50) NOT NULL,
	ESTADO       VARCHAR(30) NOT NULL,
	TELEFONE     VARCHAR(20) NOT NULL,
	CELULAR      VARCHAR(20) NOT NULL,
	EMAIL        VARCHAR(80) NOT NULL,
	SENHA        VARCHAR(80) NOT NULL,
	CADASTRO     DATE DEFAULT GETDATE()
)
GO
CREATE TABLE FUNCIONARIO (
	ID_FUNCIONARIO INT PRIMARY KEY IDENTITY(1,1),
	NOME           VARCHAR(80) NOT NULL,
	SEXO           VARCHAR(20) NOT NULL,
	RG             VARCHAR(50) NOT NULL,
	CPF            VARCHAR(50) NOT NULL,
	RUA            VARCHAR(80) NOT NULL,
	NUM            INT NOT NULL,
	BAIRRO         VARCHAR(20) NOT NULL,
	CEP            VARCHAR(9) NOT NULL,
	CIDADE         VARCHAR(50) NOT NULL,
	ESTADO         VARCHAR(30) NOT NULL,
	TELEFONE       VARCHAR(20) NOT NULL,
	CELULAR        VARCHAR(20) NOT NULL,
	EMAIL          VARCHAR(80) NOT NULL,
	SENHA          VARCHAR(80) NOT NULL,
	CARGO          INT FOREIGN KEY REFERENCES CARGO(ID_CARGO),
	CADASTRO       DATE DEFAULT GETDATE()
)
GO
CREATE TABLE ATIVIDADE (
	ID_ATIV      INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NOME         VARCHAR(40) NOT NULL,
	DESCRICAO    VARCHAR(100) NOT NULL,
	ID_PROFESSOR INT FOREIGN KEY REFERENCES PROFESSOR(ID_PROFESSOR),
	CADASTRO     DATE DEFAULT GETDATE()
)
GO
CREATE TABLE NOTA (
	ID_NOTA  INT NOT NULL IDENTITY(1,1),
	ID_ATIV  INT FOREIGN KEY REFERENCES ATIVIDADE(ID_ATIV),
	ID_ALUNO INT FOREIGN KEY REFERENCES ALUNO(ID_ALUNO),
	VALOR    INT NOT NULL
)
GO
CREATE TABLE TURMA (
	ID_TURMA INT PRIMARY KEY IDENTITY(1,1),
    ID_CURSO INT FOREIGN KEY REFERENCES CURSO(ID_CURSO)
)
GO
CREATE TABLE TURMA_ALUNO (
	ID_TURMA INT FOREIGN KEY REFERENCES TURMA(ID_TURMA),
	ID_ALUNO INT FOREIGN KEY REFERENCES ALUNO(ID_ALUNO)
)
GO
CREATE TABLE PRODUTO (
	ID_PROD   INT PRIMARY KEY IDENTITY(1,1),
	NOME_PROD VARCHAR(50) NOT NULL,
	PRECO     DECIMAL(10,2) NOT NULL,
	QNT       INT NOT NULL,
	IMAGEM    VARCHAR(50)
)
GO
CREATE TABLE PEDIDO (
	ID_PED  INT PRIMARY KEY IDENTITY(1,1),
	ID_PROD INT FOREIGN KEY REFERENCES PRODUTO(ID_PROD),
	VALOR   DECIMAL(10,2) NOT NULL,
	QUANT   INT NOT NULL
)
GO
INSERT INTO PROFESSOR VALUES('TESTE', 'TESTE', 'TESTE', 'TESTE', 'TESTE', 1, 'TESTE', 'TESTE', 'TESTE', 'TESTE', 'TESTE', 'TESTE', 'tst@com', 'teste', '10-10-1000')

